### PR TITLE
Script to uninstall AlsaMixerFreeze added

### PR DESCRIPTION
**Pull request by Blastoise**
* uninstall.sh script has been added
* README.md has been updated with **How to uninstall** section.

### CODE REVIEW

**Comment by Blastoise** [comment]
Adding **hacktoberfest-accepted** label on this pull request will be helpful for me.

**Review by Kafels — APPROVED** [review]
Well done

**Comment by Blastoise** [comment]
Thanks but please add **hacktoberfest-accepted**  label on this pull request. You have added it on the issue instead of pull request.

**Comment by Kafels** [comment]
Thank you for remembering me, added to PR

**Pull request merged**
